<?php

namespace Ais\DaftarBundle\Repository;

/**
 * DaftarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaftarRepository extends \Doctrine\ORM\EntityRepository
{
}
